### ISSUE TITLE
Case-sensitive code

### ISSUE THREAD

**Issue by caiosm1005** [caiosm1005/bcce#5]
A case-sensitive code looks closer to C and feels better organized.

All function calls will be case-sensitive.

Most keywords will be in lower-case. Here's an example of a script with the correct casing:

```
script 100 enter clientside net
{
    int a = 42;
    terminate;
}
```

**Comment by positively-charged** [comment]
I also had the desire to make it case-sensitive. I thought about doing it a few times but fought off the temptation. Being compatible as much as possible with existing code and documentation eventually prevailed.

**Comment by caiosm1005** [comment]
@wormt I'll take this oportunity to thank your for open-sourcing such fun and well-written project. I've been learning a lot just by reading the code.

I am in no way a compiler expert but I am trying to solve some of the biggest issues in the ACS language, specially math mixing integer and fixed numbers. Here is an example of how messy a script of one of my projects became by using FixedDiv / FixedMul and a bunch of bit shifting.

```
int grow = radCos(FixedMul(PI2, ((t % 24) << 16) / 24));
grow = FixedMul(grow, FixedMul(FixedDiv(max(1.0, FixedDiv(100.0, max(health << 16, 12.0))) - 1.0, 1.31), 57.0));
int anxratio = FixedDiv(anxiety, 100.0);
int anx = HUD_HEART_MIN_BEATS - (FixedMul((HUD_HEART_MIN_BEATS - HUD_HEART_MAX_BEATS) << 16, anxratio) >> 16);
tt = FixedDiv((t % anx) << 16, anx << 16);
int ttdiv  = FixedMul(max(0, tt - 0.5), 2.0);
int ttdiv2 = min(1.0, FixedMul(max(0, tt - 0.666), 3.0));
f  = FixedDiv(FixedMul(radSin(FixedMul(ttdiv, PI2)), 2.0), 1.4 + FixedMul(fpow(ttdiv, 3), 80.0));
```

Therefore I am not taking a backward-compatible approach. For this reason I forked your project instead of making suggestions / PR to your own repository.

**Comment by positively-charged** [comment]
Thanks, man. I appreciate your compliments. If you feel like you have a decent solution to this problem, then give it a try. Experiment and see how it goes.
