### ISSUE TITLE
Compile-time evaluation

### ISSUE THREAD

**Issue by caiosm1005** [caiosm1005/bcce#8]
bcc does compile-time evaluation for simple math, but it only optimizes global and map variables.

This feature should work also for script expressions, script arguments and function arguments, meeting the following criteria:
1. Solve math
2. ~~Concatenate strings~~ (moved to separate issue #9)

**Comment by positively-charged** [comment]
The back-end of the compiler does more constant folding. Any generated code scheduled to be published that looks like a mathematical operation and has constant operands will be evaluated before publication. The objectives of this final constant-folding step includes tasks like calculating the absolute offsets of structure members. The code is found in `obj.c`.

I was working on a C99-like preprocessor. With the preprocessor, strings can be concatenated using named constants. That improves the situation a little. Right now, you can only concatenate string literals. Unfortunately, I got burned out working on the preprocessor. :)
